<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DocX" Version="5.0.0" />
	<PackageReference Include="FluentDateTime" Version="3.0.0" />
    <PackageReference Include="HtmlAgilityPack" Version="1.12.4" />
	<PackageReference Include="Lorem.Universal.NET" Version="5.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components" Version="10.0.3" />
	<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.3" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.3" />
	<PackageReference Include="Radzen.Blazor" Version="9.0.8" />
  </ItemGroup>

</Project>
