version: 2
registries:
  my-nuget-feed:
    type: nuget-feed
    url: https://nuget.pkg.github.com/UoMResearchIT/index.json
    token: ${{secrets.ACTIONS_LOCAL_TOKEN}}

updates:
  - package-ecosystem: "nuget"
    directory: "/PPMTool/"  # Adjust if your .csproj is in a subfolder
    schedule:
      interval: "weekly"
    registries: "*"
