# SPDX-FileCopyrightText: 2026 University of Manchester
#
# SPDX-License-Identifier: apache-2.0

version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/PPMTool/"
    schedule:
      interval: "weekly"
    groups:
      all-nuget-updates:
        patterns:
          - "*"
    cooldown:
      default-days: 7
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all-actions-updates:
        patterns:
          - "*"
    cooldown:
      default-days: 7
