services:
  capx:
    build:
      context: .
      args:
        GITHUB_USERNAME: "$PPMTOOL_GITHUB_USERNAME"
        GITHUB_PASSWORD: "$PPMTOOL_GITHUB_PASSWORD"
    ports:
      - 80:80
      - 443:443
