// SPDX-FileCopyrightText: 2025 University of Manchester
//
// SPDX-License-Identifier: apache-2.0

﻿// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PPMTool.Data.Context;

#nullable disable

namespace PPMTool.Migrations
{
    [DbContext(typeof(PPMToolContext))]
    [Migration("20241008065707_AddedTaskNameAndDutyToInnateCode")]
    partial class AddedTaskNameAndDutyToInnateCode
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.27");

            modelBuilder.Entity("PersonProject", b =>
                {
                    b.Property<int>("FollowedProjectsProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FollowersPersonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FollowedProjectsProjectId", "FollowersPersonId");

                    b.HasIndex("FollowersPersonId");

                    b.ToTable("PersonProject");
                });

            modelBuilder.Entity("PersonSkillTag", b =>
                {
                    b.Property<int>("PeoplePersonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkillTagsSkillTagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PeoplePersonId", "SkillTagsSkillTagId");

                    b.HasIndex("SkillTagsSkillTagId");

                    b.ToTable("PersonSkillTag");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.Absence", b =>
                {
                    b.Property<int>("AbsenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("AbsenceId");

                    b.HasIndex("PersonId");

                    b.ToTable("Absence");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.FinancialReference", b =>
                {
                    b.Property<int>("FinancialReferenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FinancialYear")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Grade41Costs")
                        .HasColumnType("REAL");

                    b.Property<float>("Grade51Costs")
                        .HasColumnType("REAL");

                    b.Property<float>("Grade55Costs")
                        .HasColumnType("REAL");

                    b.Property<float>("Grade65Costs")
                        .HasColumnType("REAL");

                    b.Property<float>("Grade71Costs")
                        .HasColumnType("REAL");

                    b.Property<float>("Grade75Costs")
                        .HasColumnType("REAL");

                    b.Property<float>("RecoveryTarget")
                        .HasColumnType("REAL");

                    b.HasKey("FinancialReferenceId");

                    b.ToTable("FinancialReferences");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.InnateCode", b =>
                {
                    b.Property<int>("InnateCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActivityCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivityName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Duty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("InnateCodeId");

                    b.ToTable("InnateCodes");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.Note", b =>
                {
                    b.Property<int>("NoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorPersonId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EditedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EditorPersonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HtmlContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFinanceInfo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.HasKey("NoteId");

                    b.HasIndex("AuthorPersonId");

                    b.HasIndex("EditorPersonId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("FTE")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("PersonId");

                    b.ToTable("People");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ActualCost")
                        .HasColumnType("REAL");

                    b.Property<double>("ActualLeadershipCosts")
                        .HasColumnType("REAL");

                    b.Property<double>("ActualWorkHours")
                        .HasColumnType("REAL");

                    b.Property<string>("ActualsLastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<double>("Budget")
                        .HasColumnType("REAL");

                    b.Property<int>("CostModel")
                        .HasColumnType("INTEGER");

                    b.Property<double>("DayRate")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Faculty")
                        .HasColumnType("INTEGER");

                    b.Property<double>("FundsReceived")
                        .HasColumnType("REAL");

                    b.Property<int?>("InnateActivityInnateCodeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PI")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("PlannedCost")
                        .HasColumnType("REAL");

                    b.Property<double>("PlannedLeadershipCosts")
                        .HasColumnType("REAL");

                    b.Property<double>("PlannedWorkHours")
                        .HasColumnType("REAL");

                    b.Property<int?>("ProjectManagerPersonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RTP")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestDocLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("School")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScrumProjectLink")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectId");

                    b.HasIndex("InnateActivityInnateCodeId");

                    b.HasIndex("ProjectManagerPersonId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.Resource", b =>
                {
                    b.Property<int>("ResourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ActualCost")
                        .HasColumnType("REAL");

                    b.Property<double>("ActualWorkHours")
                        .HasColumnType("REAL");

                    b.Property<double>("AssignmentFTE")
                        .HasColumnType("REAL");

                    b.Property<double?>("DayRate")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsProvisional")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PlannedCost")
                        .HasColumnType("REAL");

                    b.Property<double>("PlannedWorkHours")
                        .HasColumnType("REAL");

                    b.Property<int?>("SubTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseProjectDayRate")
                        .HasColumnType("INTEGER");

                    b.HasKey("ResourceId");

                    b.HasIndex("PersonId");

                    b.HasIndex("SubTaskId");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CASUserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastLoggedIn")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleType")
                        .HasColumnType("INTEGER");

                    b.HasKey("RoleId");

                    b.HasIndex("PersonId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.SkillTag", b =>
                {
                    b.Property<int>("SkillTagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("SkillTagId");

                    b.ToTable("SkillTags");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.SubTask", b =>
                {
                    b.Property<int>("SubTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ActualCost")
                        .HasColumnType("REAL");

                    b.Property<double>("ActualWorkHours")
                        .HasColumnType("REAL");

                    b.Property<double>("Demand")
                        .HasColumnType("REAL");

                    b.Property<int>("DurationBillableDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DurationDays")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasFixedEndDate")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasFixedStart")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Lag")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("OriginalDemand")
                        .HasColumnType("REAL");

                    b.Property<double>("PlannedCost")
                        .HasColumnType("REAL");

                    b.Property<double>("PlannedWorkHours")
                        .HasColumnType("REAL");

                    b.Property<int?>("PredecessorSubTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TaskType")
                        .HasColumnType("INTEGER");

                    b.Property<double>("UnmetDemand")
                        .HasColumnType("REAL");

                    b.HasKey("SubTaskId");

                    b.HasIndex("PredecessorSubTaskId");

                    b.HasIndex("ProjectId");

                    b.ToTable("SubTasks");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.WorkloadModelChange", b =>
                {
                    b.Property<int>("WorkloadModelChangeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ArchitectureFTE")
                        .HasColumnType("REAL");

                    b.Property<double>("BusinessAsUsualFTE")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Grade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PersonalDevelopmentFTE")
                        .HasColumnType("REAL");

                    b.Property<double>("ProjectAndServiceManagementFTE")
                        .HasColumnType("REAL");

                    b.Property<double>("ProjectWorkFTE")
                        .HasColumnType("REAL");

                    b.Property<double>("StaffManagementFTE")
                        .HasColumnType("REAL");

                    b.HasKey("WorkloadModelChangeId");

                    b.HasIndex("PersonId");

                    b.ToTable("WorkloadModelChanges");
                });

            modelBuilder.Entity("PersonProject", b =>
                {
                    b.HasOne("PPMTool.Data.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("FollowedProjectsProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PPMTool.Data.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("FollowersPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PersonSkillTag", b =>
                {
                    b.HasOne("PPMTool.Data.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("PeoplePersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PPMTool.Data.Entities.SkillTag", null)
                        .WithMany()
                        .HasForeignKey("SkillTagsSkillTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PPMTool.Data.Entities.Absence", b =>
                {
                    b.HasOne("PPMTool.Data.Entities.Person", "Person")
                        .WithMany("Absences")
                        .HasForeignKey("PersonId");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.Note", b =>
                {
                    b.HasOne("PPMTool.Data.Entities.Person", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PPMTool.Data.Entities.Person", "Editor")
                        .WithMany()
                        .HasForeignKey("EditorPersonId");

                    b.HasOne("PPMTool.Data.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Editor");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.Project", b =>
                {
                    b.HasOne("PPMTool.Data.Entities.InnateCode", "InnateActivity")
                        .WithMany()
                        .HasForeignKey("InnateActivityInnateCodeId");

                    b.HasOne("PPMTool.Data.Entities.Person", "ProjectManager")
                        .WithMany("ManagedProjects")
                        .HasForeignKey("ProjectManagerPersonId");

                    b.Navigation("InnateActivity");

                    b.Navigation("ProjectManager");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.Resource", b =>
                {
                    b.HasOne("PPMTool.Data.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId");

                    b.HasOne("PPMTool.Data.Entities.SubTask", null)
                        .WithMany("AssignedResources")
                        .HasForeignKey("SubTaskId");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.Role", b =>
                {
                    b.HasOne("PPMTool.Data.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.SubTask", b =>
                {
                    b.HasOne("PPMTool.Data.Entities.SubTask", "Predecessor")
                        .WithMany()
                        .HasForeignKey("PredecessorSubTaskId");

                    b.HasOne("PPMTool.Data.Entities.Project", null)
                        .WithMany("SubTasks")
                        .HasForeignKey("ProjectId");

                    b.Navigation("Predecessor");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.WorkloadModelChange", b =>
                {
                    b.HasOne("PPMTool.Data.Entities.Person", "Person")
                        .WithMany("WorkloadModelChanges")
                        .HasForeignKey("PersonId");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.Person", b =>
                {
                    b.Navigation("Absences");

                    b.Navigation("ManagedProjects");

                    b.Navigation("WorkloadModelChanges");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.Project", b =>
                {
                    b.Navigation("SubTasks");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.SubTask", b =>
                {
                    b.Navigation("AssignedResources");
                });
#pragma warning restore 612, 618
        }
    }
}
