// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PPMTool.Data.Context;

#nullable disable

namespace PPMTool.Migrations
{
    [DbContext(typeof(PPMToolContext))]
    [Migration("20240109174627_ChangeColumnNamePercentageToFTEInResource")]
    partial class ChangeColumnNamePercentageToFTEInResource
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.19");

            modelBuilder.Entity("PersonSkillTag", b =>
                {
                    b.Property<int>("PeoplePersonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkillTagsSkillTagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PeoplePersonId", "SkillTagsSkillTagId");

                    b.HasIndex("SkillTagsSkillTagId");

                    b.ToTable("PersonSkillTag");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.AvailabilityChange", b =>
                {
                    b.Property<int>("AvailabilityChangeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AvailabilityFTE")
                        .HasColumnType("REAL");

                    b.Property<string>("BaselineActivities")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PersonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AvailabilityChangeId");

                    b.HasIndex("PersonId");

                    b.ToTable("AvailabilityChanges");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("DayRate")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("FTE")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("PersonId");

                    b.ToTable("People");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ActualCost")
                        .HasColumnType("REAL");

                    b.Property<double>("ActualWorkHours")
                        .HasColumnType("REAL");

                    b.Property<double>("Budget")
                        .HasColumnType("REAL");

                    b.Property<int>("BudgetStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("FundsReceived")
                        .HasColumnType("REAL");

                    b.Property<string>("InnateActivity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PI")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("PlannedCost")
                        .HasColumnType("REAL");

                    b.Property<double>("PlannedWorkHours")
                        .HasColumnType("REAL");

                    b.Property<int>("Portfolio")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProjectManagerPersonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RTP")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScheduleStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectId");

                    b.HasIndex("ProjectManagerPersonId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.Resource", b =>
                {
                    b.Property<int>("ResourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AssignmentFTE")
                        .HasColumnType("REAL");

                    b.Property<double?>("DayRate")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsProvisional")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SubTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseDefaultDayRate")
                        .HasColumnType("INTEGER");

                    b.HasKey("ResourceId");

                    b.HasIndex("PersonId");

                    b.HasIndex("SubTaskId");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CASUserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleType")
                        .HasColumnType("INTEGER");

                    b.HasKey("RoleId");

                    b.HasIndex("PersonId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.SkillTag", b =>
                {
                    b.Property<int>("SkillTagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("SkillTagId");

                    b.ToTable("SkillTags");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.SubTask", b =>
                {
                    b.Property<int>("SubTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ActualCost")
                        .HasColumnType("REAL");

                    b.Property<double>("ActualWorkHours")
                        .HasColumnType("REAL");

                    b.Property<int>("BudgetStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DurationBusinessDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DurationDays")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasFixedStart")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDone")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEndDateDriven")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWorkDriven")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("PlannedCost")
                        .HasColumnType("REAL");

                    b.Property<double>("PlannedWorkHours")
                        .HasColumnType("REAL");

                    b.Property<int?>("PredecessorSubTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScheduleStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TaskType")
                        .HasColumnType("INTEGER");

                    b.HasKey("SubTaskId");

                    b.HasIndex("PredecessorSubTaskId");

                    b.HasIndex("ProjectId");

                    b.ToTable("SubTasks");
                });

            modelBuilder.Entity("PersonSkillTag", b =>
                {
                    b.HasOne("PPMTool.Data.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("PeoplePersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PPMTool.Data.Entities.SkillTag", null)
                        .WithMany()
                        .HasForeignKey("SkillTagsSkillTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PPMTool.Data.Entities.AvailabilityChange", b =>
                {
                    b.HasOne("PPMTool.Data.Entities.Person", "Person")
                        .WithMany("AvailabilityChanges")
                        .HasForeignKey("PersonId");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.Project", b =>
                {
                    b.HasOne("PPMTool.Data.Entities.Person", "ProjectManager")
                        .WithMany()
                        .HasForeignKey("ProjectManagerPersonId");

                    b.Navigation("ProjectManager");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.Resource", b =>
                {
                    b.HasOne("PPMTool.Data.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId");

                    b.HasOne("PPMTool.Data.Entities.SubTask", null)
                        .WithMany("AssignedResources")
                        .HasForeignKey("SubTaskId");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.Role", b =>
                {
                    b.HasOne("PPMTool.Data.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.SubTask", b =>
                {
                    b.HasOne("PPMTool.Data.Entities.SubTask", "Predecessor")
                        .WithMany()
                        .HasForeignKey("PredecessorSubTaskId");

                    b.HasOne("PPMTool.Data.Entities.Project", null)
                        .WithMany("SubTasks")
                        .HasForeignKey("ProjectId");

                    b.Navigation("Predecessor");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.Person", b =>
                {
                    b.Navigation("AvailabilityChanges");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.Project", b =>
                {
                    b.Navigation("SubTasks");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.SubTask", b =>
                {
                    b.Navigation("AssignedResources");
                });
#pragma warning restore 612, 618
        }
    }
}
