// SPDX-FileCopyrightText: 2026 University of Manchester
//
// SPDX-License-Identifier: apache-2.0

// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PPMTool.Data.Context;

#nullable disable

namespace PPMTool.Migrations
{
    [DbContext(typeof(PPMToolContext))]
    partial class PPMToolContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.15");

            modelBuilder.Entity("PPMTool.Data.Entities.Absence", b =>
                {
                    b.Property<int>("AbsenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("AbsenceId");

                    b.HasIndex("PersonId");

                    b.ToTable("Absence");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.ApiKey", b =>
                {
                    b.Property<int>("ApiKeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ApiKeyId");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.Competency", b =>
                {
                    b.Property<int>("CompetencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Grade")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LegacyId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RevisionDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CompetencyId");

                    b.ToTable("Competencies");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.CompetencyAssessment", b =>
                {
                    b.Property<int>("CompetencyAssessmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompetencyDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CompetencyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompetencyObjective")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CompetencyRevision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DateCreated")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Evidence")
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("CompetencyAssessmentId");

                    b.HasIndex("CompetencyId");

                    b.HasIndex("PersonId");

                    b.ToTable("CompetencyAssessments");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.Faculty", b =>
                {
                    b.Property<int>("FacultyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FacultyId");

                    b.ToTable("Faculties");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.FinancialReference", b =>
                {
                    b.Property<int>("FinancialReferenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FinancialYear")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Grade41Costs")
                        .HasColumnType("REAL");

                    b.Property<float>("Grade51Costs")
                        .HasColumnType("REAL");

                    b.Property<float>("Grade55Costs")
                        .HasColumnType("REAL");

                    b.Property<float>("Grade65Costs")
                        .HasColumnType("REAL");

                    b.Property<float>("Grade71Costs")
                        .HasColumnType("REAL");

                    b.Property<float>("Grade75Costs")
                        .HasColumnType("REAL");

                    b.Property<float>("RecoveryTarget")
                        .HasColumnType("REAL");

                    b.HasKey("FinancialReferenceId");

                    b.ToTable("FinancialReferences");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.FundingSource", b =>
                {
                    b.Property<int>("FundingSourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountCode")
                        .HasColumnType("TEXT");

                    b.Property<double>("AmountAvailable")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("FundingSourceType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasAccountCode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FundingSourceId");

                    b.HasIndex("ProjectId");

                    b.ToTable("FundingSources");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.InnateCode", b =>
                {
                    b.Property<int>("InnateCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActivityCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivityName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSensitive")
                        .HasColumnType("INTEGER");

                    b.HasKey("InnateCodeId");

                    b.ToTable("InnateCodes");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.InnateCodeTask", b =>
                {
                    b.Property<int>("InnateCodeTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Duty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InnateCodeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("InnateCodeTaskId");

                    b.HasIndex("InnateCodeId");

                    b.ToTable("InnateCodeTasks");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceReference")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("KeyDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("InvoiceId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.Note", b =>
                {
                    b.Property<int>("NoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EditedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EditorUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HtmlContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFinanceInfo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.HasKey("NoteId");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("EditorUserId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.OwnedSkill", b =>
                {
                    b.Property<int>("OwnedSkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FavouriteSkill")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUsed")
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerPersonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Proficiency")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkillTagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("OwnedSkillId");

                    b.HasIndex("OwnerPersonId");

                    b.HasIndex("SkillTagId");

                    b.ToTable("OwnedSkills");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("KeyDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceFundingSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("PaymentId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SourceFundingSourceId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("FTE")
                        .HasColumnType("REAL");

                    b.Property<int?>("LineManagerPersonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TimesheetTemplateData")
                        .HasColumnType("TEXT");

                    b.HasKey("PersonId");

                    b.HasIndex("LineManagerPersonId");

                    b.ToTable("People");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ActualCost")
                        .HasColumnType("REAL");

                    b.Property<double>("ActualIndirectCost")
                        .HasColumnType("REAL");

                    b.Property<double>("ActualLeadershipCosts")
                        .HasColumnType("REAL");

                    b.Property<double>("ActualWorkHours")
                        .HasColumnType("REAL");

                    b.Property<string>("ActualsLastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<double>("Budget")
                        .HasColumnType("REAL");

                    b.Property<double>("BudgetedIndirects")
                        .HasColumnType("REAL");

                    b.Property<int>("CostModel")
                        .HasColumnType("INTEGER");

                    b.Property<double>("DayRate")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FundingSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InnateActivityInnateCodeId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("LeadershipFTE")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PI")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("PlannedCost")
                        .HasColumnType("REAL");

                    b.Property<double>("PlannedIndirectCost")
                        .HasColumnType("REAL");

                    b.Property<double>("PlannedLeadershipCosts")
                        .HasColumnType("REAL");

                    b.Property<double>("PlannedWorkHours")
                        .HasColumnType("REAL");

                    b.Property<int?>("ProjectManagerPersonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RTP")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestDocLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SchoolId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScrumProjectLink")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectId");

                    b.HasIndex("FundingSourceId")
                        .IsUnique();

                    b.HasIndex("InnateActivityInnateCodeId");

                    b.HasIndex("ProjectManagerPersonId");

                    b.HasIndex("SchoolId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.Resource", b =>
                {
                    b.Property<int>("ResourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ActualCost")
                        .HasColumnType("REAL");

                    b.Property<double>("ActualIndirectCost")
                        .HasColumnType("REAL");

                    b.Property<double>("ActualWorkHours")
                        .HasColumnType("REAL");

                    b.Property<double>("AssignmentFTE")
                        .HasColumnType("REAL");

                    b.Property<double>("BilledFTE")
                        .HasColumnType("REAL");

                    b.Property<double?>("DayRate")
                        .HasColumnType("REAL");

                    b.Property<int?>("FundedFromFundingSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsProvisional")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PlannedCost")
                        .HasColumnType("REAL");

                    b.Property<double>("PlannedIndirectCost")
                        .HasColumnType("REAL");

                    b.Property<double>("PlannedWorkHours")
                        .HasColumnType("REAL");

                    b.Property<int>("SubTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseProjectDayRate")
                        .HasColumnType("INTEGER");

                    b.HasKey("ResourceId");

                    b.HasIndex("FundedFromFundingSourceId");

                    b.HasIndex("PersonId");

                    b.HasIndex("SubTaskId");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.School", b =>
                {
                    b.Property<int>("SchoolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FacultyId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SchoolId");

                    b.HasIndex("FacultyId");

                    b.ToTable("Schools");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.SkillTag", b =>
                {
                    b.Property<int>("SkillTagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ControlledName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HasValidWikiLink")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rareness")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RarenessCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("SkillTagId");

                    b.ToTable("SkillTags");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.SubTask", b =>
                {
                    b.Property<int>("SubTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ActualCost")
                        .HasColumnType("REAL");

                    b.Property<double>("ActualIndirectCost")
                        .HasColumnType("REAL");

                    b.Property<double>("ActualWorkHours")
                        .HasColumnType("REAL");

                    b.Property<double>("Demand")
                        .HasColumnType("REAL");

                    b.Property<int>("DurationBillableDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DurationDays")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasFixedEndDate")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasFixedStart")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Lag")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("OriginalDemand")
                        .HasColumnType("REAL");

                    b.Property<int?>("OwningProjectProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PlannedCost")
                        .HasColumnType("REAL");

                    b.Property<double>("PlannedIndirectCost")
                        .HasColumnType("REAL");

                    b.Property<double>("PlannedWorkHours")
                        .HasColumnType("REAL");

                    b.Property<int?>("PredecessorSubTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequiresLeadership")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TaskType")
                        .HasColumnType("INTEGER");

                    b.Property<double>("UnmetDemand")
                        .HasColumnType("REAL");

                    b.HasKey("SubTaskId");

                    b.HasIndex("OwningProjectProjectId");

                    b.HasIndex("PredecessorSubTaskId");

                    b.ToTable("SubTasks");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.Timesheet", b =>
                {
                    b.Property<int>("TimesheetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateStatusChanged")
                        .HasColumnType("TEXT");

                    b.Property<string>("Info")
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StatusChangedByPersonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TimesheetId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("StatusChangedByPersonId");

                    b.ToTable("Timesheets");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.TimesheetEntry", b =>
                {
                    b.Property<int>("TimesheetEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("FridayHours")
                        .HasColumnType("REAL");

                    b.Property<int>("InnateCodeTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MondayHours")
                        .HasColumnType("REAL");

                    b.Property<double>("SaturdayHours")
                        .HasColumnType("REAL");

                    b.Property<double>("SundayHours")
                        .HasColumnType("REAL");

                    b.Property<double>("ThursdayHours")
                        .HasColumnType("REAL");

                    b.Property<int>("TimesheetId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TuesdayHours")
                        .HasColumnType("REAL");

                    b.Property<double>("WednesdayHours")
                        .HasColumnType("REAL");

                    b.HasKey("TimesheetEntryId");

                    b.HasIndex("InnateCodeTaskId");

                    b.HasIndex("TimesheetId");

                    b.ToTable("TimesheetEntries");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CASUserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastLoggedIn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleType")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.HasIndex("PersonId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.WorkloadModelChange", b =>
                {
                    b.Property<int>("WorkloadModelChangeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ArchitectureFTE")
                        .HasColumnType("REAL");

                    b.Property<double>("BusinessAsUsualFTE")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Grade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PersonalDevelopmentFTE")
                        .HasColumnType("REAL");

                    b.Property<double>("ProjectAndServiceManagementFTE")
                        .HasColumnType("REAL");

                    b.Property<double>("ProjectManagementFTE")
                        .HasColumnType("REAL");

                    b.Property<double>("ProjectWorkFTE")
                        .HasColumnType("REAL");

                    b.Property<double>("ServiceManagementFTE")
                        .HasColumnType("REAL");

                    b.Property<double>("StaffManagementFTE")
                        .HasColumnType("REAL");

                    b.HasKey("WorkloadModelChangeId");

                    b.HasIndex("PersonId");

                    b.ToTable("WorkloadModelChanges");
                });

            modelBuilder.Entity("PersonProject", b =>
                {
                    b.Property<int>("FollowedProjectsProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FollowersPersonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FollowedProjectsProjectId", "FollowersPersonId");

                    b.HasIndex("FollowersPersonId");

                    b.ToTable("PersonProject");
                });

            modelBuilder.Entity("SkillTagSubTask", b =>
                {
                    b.Property<int>("SkillsRequiredSkillTagId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TasksNeedingThisSkillSubTaskId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SkillsRequiredSkillTagId", "TasksNeedingThisSkillSubTaskId");

                    b.HasIndex("TasksNeedingThisSkillSubTaskId");

                    b.ToTable("SkillTagSubTask");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.Absence", b =>
                {
                    b.HasOne("PPMTool.Data.Entities.Person", "Person")
                        .WithMany("Absences")
                        .HasForeignKey("PersonId");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.ApiKey", b =>
                {
                    b.HasOne("PPMTool.Data.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.CompetencyAssessment", b =>
                {
                    b.HasOne("PPMTool.Data.Entities.Competency", null)
                        .WithMany("Assessments")
                        .HasForeignKey("CompetencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PPMTool.Data.Entities.Person", null)
                        .WithMany("Assessments")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PPMTool.Data.Entities.FundingSource", b =>
                {
                    b.HasOne("PPMTool.Data.Entities.Project", "Project")
                        .WithMany("FundingSources")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.InnateCodeTask", b =>
                {
                    b.HasOne("PPMTool.Data.Entities.InnateCode", "InnateCode")
                        .WithMany("Tasks")
                        .HasForeignKey("InnateCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InnateCode");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.Invoice", b =>
                {
                    b.HasOne("PPMTool.Data.Entities.Project", "Project")
                        .WithMany("Invoices")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.Note", b =>
                {
                    b.HasOne("PPMTool.Data.Entities.User", "Author")
                        .WithMany("AuthoredNotes")
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PPMTool.Data.Entities.User", "Editor")
                        .WithMany("EditedNotes")
                        .HasForeignKey("EditorUserId");

                    b.HasOne("PPMTool.Data.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Editor");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.OwnedSkill", b =>
                {
                    b.HasOne("PPMTool.Data.Entities.Person", "Owner")
                        .WithMany("OwnedSkills")
                        .HasForeignKey("OwnerPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PPMTool.Data.Entities.SkillTag", "SkillTag")
                        .WithMany("OwnedSkills")
                        .HasForeignKey("SkillTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("SkillTag");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.Payment", b =>
                {
                    b.HasOne("PPMTool.Data.Entities.Invoice", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId");

                    b.HasOne("PPMTool.Data.Entities.Project", "Project")
                        .WithMany("Payments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PPMTool.Data.Entities.FundingSource", "Source")
                        .WithMany("PaymentsFromSource")
                        .HasForeignKey("SourceFundingSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Project");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.Person", b =>
                {
                    b.HasOne("PPMTool.Data.Entities.Person", "LineManager")
                        .WithMany("PeopleManaged")
                        .HasForeignKey("LineManagerPersonId");

                    b.Navigation("LineManager");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.Project", b =>
                {
                    b.HasOne("PPMTool.Data.Entities.FundingSource", "LeadershipFundingSource")
                        .WithOne("ProjectLeadershipSource")
                        .HasForeignKey("PPMTool.Data.Entities.Project", "FundingSourceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PPMTool.Data.Entities.InnateCode", "InnateActivity")
                        .WithMany()
                        .HasForeignKey("InnateActivityInnateCodeId");

                    b.HasOne("PPMTool.Data.Entities.Person", "ProjectManager")
                        .WithMany("ManagedProjects")
                        .HasForeignKey("ProjectManagerPersonId");

                    b.HasOne("PPMTool.Data.Entities.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InnateActivity");

                    b.Navigation("LeadershipFundingSource");

                    b.Navigation("ProjectManager");

                    b.Navigation("School");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.Resource", b =>
                {
                    b.HasOne("PPMTool.Data.Entities.FundingSource", "FundedFrom")
                        .WithMany("ResourcesFunded")
                        .HasForeignKey("FundedFromFundingSourceId");

                    b.HasOne("PPMTool.Data.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PPMTool.Data.Entities.SubTask", "SubTask")
                        .WithMany("AssignedResources")
                        .HasForeignKey("SubTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FundedFrom");

                    b.Navigation("Person");

                    b.Navigation("SubTask");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.School", b =>
                {
                    b.HasOne("PPMTool.Data.Entities.Faculty", "Faculty")
                        .WithMany("Schools")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.SubTask", b =>
                {
                    b.HasOne("PPMTool.Data.Entities.Project", "OwningProject")
                        .WithMany("SubTasks")
                        .HasForeignKey("OwningProjectProjectId");

                    b.HasOne("PPMTool.Data.Entities.SubTask", "Predecessor")
                        .WithMany("Successors")
                        .HasForeignKey("PredecessorSubTaskId");

                    b.Navigation("OwningProject");

                    b.Navigation("Predecessor");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.Timesheet", b =>
                {
                    b.HasOne("PPMTool.Data.Entities.Person", "Owner")
                        .WithMany("Timesheets")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PPMTool.Data.Entities.Person", "StatusChangedBy")
                        .WithMany("TimesheetsChanged")
                        .HasForeignKey("StatusChangedByPersonId");

                    b.Navigation("Owner");

                    b.Navigation("StatusChangedBy");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.TimesheetEntry", b =>
                {
                    b.HasOne("PPMTool.Data.Entities.InnateCodeTask", "InnateCodeTask")
                        .WithMany()
                        .HasForeignKey("InnateCodeTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PPMTool.Data.Entities.Timesheet", "Timesheet")
                        .WithMany("TimesheetEntries")
                        .HasForeignKey("TimesheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InnateCodeTask");

                    b.Navigation("Timesheet");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.User", b =>
                {
                    b.HasOne("PPMTool.Data.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.WorkloadModelChange", b =>
                {
                    b.HasOne("PPMTool.Data.Entities.Person", "Person")
                        .WithMany("WorkloadModelChanges")
                        .HasForeignKey("PersonId");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("PersonProject", b =>
                {
                    b.HasOne("PPMTool.Data.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("FollowedProjectsProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PPMTool.Data.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("FollowersPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SkillTagSubTask", b =>
                {
                    b.HasOne("PPMTool.Data.Entities.SkillTag", null)
                        .WithMany()
                        .HasForeignKey("SkillsRequiredSkillTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PPMTool.Data.Entities.SubTask", null)
                        .WithMany()
                        .HasForeignKey("TasksNeedingThisSkillSubTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PPMTool.Data.Entities.Competency", b =>
                {
                    b.Navigation("Assessments");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.Faculty", b =>
                {
                    b.Navigation("Schools");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.FundingSource", b =>
                {
                    b.Navigation("PaymentsFromSource");

                    b.Navigation("ProjectLeadershipSource");

                    b.Navigation("ResourcesFunded");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.InnateCode", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.Invoice", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.Person", b =>
                {
                    b.Navigation("Absences");

                    b.Navigation("Assessments");

                    b.Navigation("ManagedProjects");

                    b.Navigation("OwnedSkills");

                    b.Navigation("PeopleManaged");

                    b.Navigation("Timesheets");

                    b.Navigation("TimesheetsChanged");

                    b.Navigation("WorkloadModelChanges");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.Project", b =>
                {
                    b.Navigation("FundingSources");

                    b.Navigation("Invoices");

                    b.Navigation("Payments");

                    b.Navigation("SubTasks");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.SkillTag", b =>
                {
                    b.Navigation("OwnedSkills");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.SubTask", b =>
                {
                    b.Navigation("AssignedResources");

                    b.Navigation("Successors");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.Timesheet", b =>
                {
                    b.Navigation("TimesheetEntries");
                });

            modelBuilder.Entity("PPMTool.Data.Entities.User", b =>
                {
                    b.Navigation("AuthoredNotes");

                    b.Navigation("EditedNotes");
                });
#pragma warning restore 612, 618
        }
    }
}
