// SPDX-FileCopyrightText: 2026 University of Manchester
//
// SPDX-License-Identifier: Apache-2.0
// SPDX-License-Identifier: apache-2.0

namespace PPMTool.Enums
{
    /// <summary>
    /// Logic as to whether the leadership tasks should be generated by the assignment chunk generator
    /// </summary>
    public enum GenerateLeadershipTaskLogic
    {
        /// <summary>
        ///  Will not generate any leadership tasks
        /// </summary>
        None,

        /// <summary>
        /// Will generate leadership tasks only if the cost model is a leadership model
        /// </summary>
        CostModel,

        /// <summary>
        /// Will generate leadership tasks for all projects regardless of cost model
        /// </summary>
        Always
    }
}
