namespace PPMTool.Enums
{
    /// <summary>
    /// Logic as to whether the leadership tasks should be generated by the assignment chunk generator
    /// </summary>
    public enum IncludeLeadershipTaskLogic
    {
        /// <summary>
        ///  Will not generate any leadership tasks
        /// </summary>
        None,

        /// <summary>
        /// Will generate leadership tasks only if the cost model is a leadership model
        /// </summary>
        CostModel,

        /// <summary>
        /// Will generate leadership tasks for all projects regardless of cost model
        /// </summary>
        Always
    }
}
