# GitHub Actions Workflow: Check Repository Ruleset
# 
# This workflow ensures that the repository's branch protection rules
# match the expected ruleset defined in '.github/Key Branch Protection Rules.json'.
#
# It runs on pushes to the main branch and pull requests.
#
# Steps:
# 1. Check out the repository.
# 2. Install jq for JSON processing.
# 3. Load expected Branch Protection Rulesets defined by RSE Department from manually exported json file.
# 4. Fetch the working repository's Branch Protection Rulesets from GitHub API.
# 5. Compare the expected and actual rulesets.

# Copyright (c) 2025 The University of Manchester
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Check Repository Ruleset

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  check-ruleset:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set executable permissions
        run: chmod +x .github/workflows/ruleset/fetch.bash && chmod +x .github/workflows/ruleset/check.bash

      - name: Fetch Standard RSE Ruleset
        id: expected
        run: .github/workflows/ruleset/fetch.bash
        env:
          GH_TOKEN: ${{ secrets.ACTIONS_REPO_TOKEN || secrets.GITHUB_TOKEN }}
          REPO_NAME: UoMResearchIT/RSE-Repository-Template

      - name: Fetch Current Repository Ruleset from GitHub API
        id: current
        run: .github/workflows/ruleset/fetch.bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_NAME: ${{ github.repository }}

      - name: Compare Rulesets
        run: .github/workflows/ruleset/check.bash
        env:
          EXPECTED_FILE: ${{ steps.expected.outputs.file }}
          CURRENT_FILE: ${{ steps.current.outputs.file }}
