# GitHub Actions Workflow: Check Repository Ruleset
#
# This workflow ensures that the repository's branch protection rules
# match the expected ruleset defined in the template repository.
#
# It runs on pushes to the main branch and pull requests.
#
# Steps:
# 1. Fetch the expected Branch Protection Rulesets from the template repository.
# 2. Fetch the current repository's Branch Protection Rulesets.
# 3. Compare the expected and actual rulesets.

# Copyright (c) 2025 The University of Manchester
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Check Repository Ruleset

on:
  push:
    branches: [dev]
  pull_request:

permissions:
  contents: read
jobs:
  check:
    if: github.repository_owner == 'UoMResearchIT'
    name: Check Ruleset
    uses: UoMResearchIT/actions/.github/workflows/check-ruleset.yaml@8839be4e18a5a880aa052da40d9730445bb42e99 # temporary feature branch that allows "ignore" argument
    with:
      bot-id: ${{ vars.ORG_ACTIONS_BOT_APP_ID }}
      ignore: '["require_code_owner_review"]'
    secrets:
      bot-key: ${{ secrets.ORG_ACTIONS_BOT_PRIVATE_KEY }}
