# This workflow will check formatting and build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: C# .NET

on:
  push:
    branches: [dev]
  pull_request:

jobs:
  format-check:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./PPMTool
    permissions:
      contents: read

    steps:
      - name: Create GitHub App token
        id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ vars.ORG_ACTIONS_BOT_APP_ID }}
          private-key: ${{ secrets.ORG_ACTIONS_BOT_PRIVATE_KEY }}
          owner: UoMResearchIT
          # NB: No current submodules; the .gitmodules file is empty
          repositories: CapX
          permission-contents: read

      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          submodules: 'true'
          token: ${{ steps.app-token.outputs.token }}
          persist-credentials: false

      - name: Setup .NET
        uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5.2.0
        with:
          dotnet-version: 10.0.x

      - name: Format
        run: dotnet format PPMTool.sln --verify-no-changes --no-restore --verbosity detailed
