# SPDX-FileCopyrightText: 2026 University of Manchester
#
# SPDX-License-Identifier: apache-2.0

name: Add Licence and Copyright Headers

on: pull_request

jobs:
  add-headers:
    permissions:
      pull-requests: write
      contents: write
    uses: UoMResearchIT/actions/.github/workflows/apply-reuse.yml@82e3b6b26f5a4435f5fc1c5b1d56b036b7b50d3d # main
