# SPDX-FileCopyrightText: 2026 University of Manchester
#
# SPDX-License-Identifier: apache-2.0

name: Add Licence and Copyright Headers

on: pull_request

jobs:
  add-headers:
    permissions:
      pull-requests: write
      contents: write
    uses: UoMResearchIT/actions/.github/workflows/apply-reuse.yml@20365fa75ab643043ec188ef0b67fd5e537d326c # main
