name: Enforce Handbook Naming Conventions

on:
  create:
  pull_request:
    branches:
      - '**'
permissions: {}

jobs:
  check-repo-name-conventions:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Check repository name
        run: |
          REPO_NAME=${REPO_NAME##*/}
          if [[ ! "$REPO_NAME" =~ ^([A-Z][A-Za-z0-9]*)(-[A-Z][A-Za-z0-9]*)*$ ]]; then
            echo "Repository name '$REPO_NAME' does not follow the naming convention established in the RSE Agile Method Handbook."
            exit 1
          fi
        env:
          REPO_NAME: ${{ github.repository }}

  check-branch-name-conventions:
    if: github.event_name == 'pull_request' && github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Check branch name
        run: |
          if [[ ! "$BRANCH_NAME" =~ ^[a-z0-9]+(-[a-z0-9]+)*$ ]]; then
            echo "Branch name '$BRANCH_NAME' does not follow the naming convention established in the RSE Agile Method Handbook."
            exit 1
          fi
        env:
          BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
